// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelCheck():Promise<void>;

export function CheckFileSizeConcurrent(arg1:Array<string>,arg2:number,arg3:string):Promise<Array<main.Result>>;
